# save1/config.py

CONFIG = {
    "KUCOIN_API_KEY": "644af066dbf5e20001001f20",
    "KUCOIN_API_SECRET": "1d57e017-1d91-44e4-bd2f-7c9e77f72700",
    "KUCOIN_API_PASSPHRASE": "ilovesophia",

    "SIMULATE": False,  # ✅ 真实交易已启用
    "SERVER_CHAN_KEY": "SCT290772THBFAsWEtLa29M3l98qRSZ1DZ",

    "TRADE": {
        "TAKE_PROFIT": 0.045,
        "STOP_LOSS": -0.025
    },

    "STRATEGY": {
        "MACD_WEIGHT": 0.3,
        "RSI_WEIGHT": 0.2,
        "SMA_WEIGHT": 0.2,
        "MOMENTUM_WEIGHT": 0.2,
        "TREND_WEIGHT": 0.1
    },

    "LOG_DIR": "/home/linuxuser/trade_logs/"
}

# 保持兼容性（旧模块使用）
KUCOIN_API_KEY = CONFIG["KUCOIN_API_KEY"]
KUCOIN_API_SECRET = CONFIG["KUCOIN_API_SECRET"]
KUCOIN_API_PASSPHRASE = CONFIG["KUCOIN_API_PASSPHRASE"]
SIMULATE = CONFIG["SIMULATE"]
SERVER_CHAN_KEY = CONFIG["SERVER_CHAN_KEY"]
TRADE = CONFIG["TRADE"]
STRATEGY = CONFIG["STRATEGY"]
LOG_DIR = CONFIG["LOG_DIR"]